stages:
  - lint
  - example_validation
  - compatibility

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_COMMIT_BRANCH == "main"'

lint_openapi_files:
  stage: lint
  image: docker:cli
  services:
    - docker:dind
  script:
    - >-
      docker run --rm
      -v "$CI_PROJECT_DIR:/usr/src/app"
      -w /usr/src/app
      -e SPECMATIC_LICENSE_CONTENT="$SPECMATIC_LICENSE_KEY"
      specmatic/enterprise
      lint 'io/specmatic/examples/store/openapi/*.yaml'

validate_openapi_examples:
  stage: example_validation
  image:
    name: specmatic/enterprise
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.specmatic && echo "$SPECMATIC_LICENSE_KEY" > ~/.specmatic/specmatic-license.txt
  script:
    - specmatic examples validate --specs-dir=io/specmatic/examples/store/openapi

compatibility:
  stage: compatibility
  image:
    name: specmatic/enterprise
    entrypoint: [""]
  variables:
    SPECMATIC_LICENSE_CONTENT: $SPECMATIC_LICENSE_KEY
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - when: never
  before_script:
    - git fetch --unshallow || true
    - git fetch origin main
  script:
    - specmatic backward-compatibility-check --base-branch=origin/main
  artifacts:
    when: always # Upload even if the backward compatibility check fails
    paths:
      - build/reports/specmatic/backward_compatibility/ctrf/*.json
